%global debug_package %{nil}
%global forgeurl https://github.com/atar-axis/xpadneo

Name: xpadneo
Version: 0.9.1
Release: 1%{?dist}
Summary: Advanced linux driver for Xbox One Wireless Gamepad

%forgemeta

# The license in the repository says GPLv3 but it was autogenerated by Github.
# The module declares its license as GPL, which in a kernel module means GPLv2.
License: GPLv2
URL: %{forgeurl}
Source0: %{forgesource}

Provides: %{name}-kmod-common = %{version}
Requires: %{name}-kmod >= %{version}

BuildRequires: systemd-rpm-macros

%description
Advanced Linux Driver for Xbox One Wireless Controller (shipped with Xbox One S)

%prep
%forgeautosetup

%build
# No build

%install
install -Dpm 0644 hid-xpadneo/etc-modprobe.d/xpadneo.conf %{buildroot}%{_modprobedir}/xpadneo.conf
install -Dpm 0644 hid-xpadneo/etc-udev-rules.d/50-xpadneo-fixup-steamlink.rules %{buildroot}%{_udevrulesdir}/50-xpadneo-fixup-steamlink.rules
install -Dpm 0644 hid-xpadneo/etc-udev-rules.d/60-xpadneo.rules %{buildroot}%{_udevrulesdir}/60-xpadneo.rules

%files
%{_modprobedir}/xpadneo.conf
%{_udevrulesdir}/50-xpadneo-fixup-steamlink.rules
%{_udevrulesdir}/60-xpadneo.rules
  
%changelog
* Fri Jul 16 2021 Dorian Stoll <dorian.stoll@tmsp.io> - 0.9.1-1
- Initial package
